### ISSUE TITLE
Code it in another programming lang

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/lolicon#7]
Bet

**Comment by DongDuong9E** [comment]
#8 Ported it to Python 3 for some reason.

**Comment by sr229** [comment]
Python part is done, now who's the next madlad who want to commit another language

**Comment by DongDuong9E** [comment]
Bet

**Comment by DongDuong9E** [comment]
Memory safe lolicon go brrr #10

**Comment by sr229** [comment]
Looks like this has been fulfilled so this is now closed.

**Comment by E404NNF** [comment]
Shouldn't have made this issue ;)
